dependencies:
  - name: gh-app-level-backend-module-new-chart
    repository: https://artifactory.dagility.com/artifactory/helm/
    version: 0.1.0
  - name: gh-app-level-backend-chart
    repository: https://artifactory.dagility.com/artifactory/helm/
    version: 0.1.0
  - name: gh-app-level-frontend-chart
    repository: https://artifactory.dagility.com/artifactory/helm/
    version: 0.1.0
