gh-app-level-new-chart:
  image:
    repository: artifactory.dagility.com/docker/repo
    tag: latest
    pullPolicy: Always
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx-internal
    hosts:
    - host: host
      paths:
      - /
  serviceAccount:
    create: false

gh-app-level-backend-module-new-new-chart:
  image:
    repository: artifactory.dagility.com/docker/gh-app-level-backend-module-new-new
    tag: latest
    pullPolicy: Always
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx-internal
    hosts:
    - host: gh-app-level-backend-module-new-new-default.dagility.com
      paths:
      - /
  serviceAccount:
    create: false

gh-app-level-backend-module-new-chart:
  image:
    repository: artifactory.dagility.com/docker/gh-app-level-backend-module-new
    tag: latest
    pullPolicy: Always
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx-internal
    hosts:
    - host: gh-app-level-backend-module-new-default.dagility.com
      paths:
      - /
  serviceAccount:
    create: false

gh-app-level-backend-chart:
  image:
    repository: artifactory.dagility.com/docker/gh-app-level-backend
    tag: latest
    pullPolicy: Always
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx-internal
    hosts:
    - host: gh-app-level-backend-default.dagility.com
      paths:
      - /
  serviceAccount:
    create: false

gh-app-level-frontend-chart:
  image:
    repository: artifactory.dagility.com/docker/gh-app-level-frontend
    tag: latest
    pullPolicy: Always
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx-internal
    hosts:
    - host: gh-app-level-frontend-default.dagility.com
      paths:
      - /
  serviceAccount:
    create: false
